"""Example pyoas plugin — copyright header injection.

This plugin prepends a custom copyright header to every generated Pydantic
model file. It demonstrates the ``on_model_file_written`` hook.

Activation in ``pyoas.yaml``::

    plugins:
      - myapp_plugin:HeaderPlugin

Or install as a package entry-point::

    [project.entry-points."pyoas.plugins"]
    header = "myapp_plugin:HeaderPlugin"
"""

from __future__ import annotations

from typing import Any


class HeaderPlugin:
    """Prepend a copyright header to every generated model file."""

    name = "header_plugin"
    version = "1.0.0"

    HEADER = (
        "# ----------------------------------------------------------------\n"
        "# Auto-generated by pyoas. DO NOT EDIT.\n"
        "# Copyright (c) 2026 My Company. All rights reserved.\n"
        "# ----------------------------------------------------------------\n"
    )

    def on_spec_loaded(
        self, spec: dict[str, Any], resolved: dict[str, Any]
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        # This plugin does not modify the spec.
        return spec, resolved

    def on_model_file_written(self, tag: str, path: str, content: str) -> str:
        """Prepend the copyright header to every model file."""
        return self.HEADER + content

    def on_router_file_written(self, tag: str, path: str, content: str) -> str:
        # This plugin does not modify router files.
        return content

    def on_generate_complete(self, stats: dict[str, Any]) -> None:
        files = stats.get("files_written", 0)
        print(f"[header_plugin] Generation complete: {files} file(s) written.")
