"""Shared string utility functions for pyoas."""

from __future__ import annotations

import hashlib
import re
import subprocess  # nosec B404
from pathlib import Path


def to_snake_case(name: str) -> str:
    """Convert a camelCase or PascalCase string to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def to_pascal_case(name: str) -> str:
    """Convert snake_case, kebab-case, or space-separated words to PascalCase."""
    return "".join(word.capitalize() for word in re.split(r"[_\-\s]+", name) if word)


def derive_import_path(path: str, source_root: str = "src") -> str:
    """Convert a filesystem output path to a dotted Python import path.

    Strips the leading source_root segment when present, so that src-layout
    projects (where ``src/`` is not a Python package) produce correct import paths.

    Examples::

        derive_import_path("src/generated/models", "src") -> "generated.models"
        derive_import_path("generated/models", "src")     -> "generated.models"
        derive_import_path("src/generated/models", "")    -> "src.generated.models"
    """
    segments = path.replace("\\", "/").strip("/").split("/")
    if source_root and segments and segments[0] == source_root.strip("/"):
        segments = segments[1:]
    return ".".join(segments)


def ensure_intermediate_inits(
    output_root: Path,
    source_root: str = "src",
    project_root: Path | None = None,
) -> None:
    """Create empty ``__init__.py`` files in directories between the layout
    root and *output_root* so they are importable as Python packages.

    Two modes depending on *source_root*:

    * ``source_root="src"`` (default, src-layout): walks up from
      ``output_root.parent`` and stops *at* the ``src/`` directory, so only
      intermediate dirs inside ``src/`` receive ``__init__.py``.
      Example: ``src/generated/models`` → creates ``src/generated/__init__.py``.

    * ``source_root=""`` (flat-layout, ``src/`` is itself a package): walks up
      from ``output_root.parent`` and stops *at* ``project_root``, stamping
      every intermediate dir including ``src/`` itself.
      Example: ``src/generated/models`` → creates ``src/__init__.py`` and
      ``src/generated/__init__.py``.

    Does nothing when the stop boundary is not found in the ancestry.
    """
    dirs_to_stamp: list[Path] = []
    current = output_root.parent

    if source_root:
        stop_name = Path(source_root).name
        while current != current.parent:
            if current.name == stop_name:
                break
            dirs_to_stamp.append(current)
            current = current.parent
        else:
            return  # stop_name not found — do nothing
    else:
        if project_root is None:
            return
        while current != current.parent:
            if current == project_root:
                break
            dirs_to_stamp.append(current)
            current = current.parent
        else:
            return  # project_root not found in ancestry — do nothing

    for d in dirs_to_stamp:
        init = d / "__init__.py"
        if not init.exists():
            init.write_text(
                "# Generated by pyoas — do not edit manually.\n", encoding="utf-8"
            )


def spec_hash_of_file(path: str) -> str:
    """Return the first 8 hex chars of the SHA-256 digest of the file at *path*."""
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()[:8]


def generate_function_name(method: str, path: str) -> str:
    """Generate a snake_case function name from an HTTP method and path."""
    slug = re.sub(r"[^a-zA-Z0-9]", "_", path).strip("_")
    slug = re.sub(r"_+", "_", slug).lower()
    method = method.lower()

    # If the slug already starts with the method (e.g. /get-users), don't double it
    if slug.startswith(f"{method}_") or slug == method:
        return slug

    return f"{method}_{slug}"


def tag_to_dirname(tag: str) -> str:
    """Convert a tag name to a safe filesystem directory/module name."""
    return re.sub(r"[^a-z0-9_]", "_", tag.lower()).strip("_")


def format_output(output_root: Path) -> None:
    """Run ``ruff format`` on *output_root* (best-effort, silently ignored on failure)."""
    try:
        subprocess.run(  # nosec
            ["ruff", "format", str(output_root)],
            check=True,
            capture_output=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
